export const DEMO_STUDENTS = [
  { key:'amina',  name:'Amina Yusuf',    email:'amina.yusuf@students.bowiestate.edu',    country:'Somalia',   major:'Computer Science' },
  { key:'carlos', name:'Carlos Mendoza', email:'carlos.mendoza@students.bowiestate.edu', country:'Mexico',    major:'Business Admin' },
  { key:'priya',  name:'Priya Nair',     email:'priya.nair@students.bowiestate.edu',     country:'India',     major:'Biology' },
  { key:'kofi',   name:'Kofi Mensah',    email:'kofi.mensah@students.bowiestate.edu',    country:'Ghana',     major:'Engineering' },
  { key:'linh',   name:'Linh Tran',      email:'linh.tran@students.bowiestate.edu',      country:'Vietnam',   major:'Nursing' },
  { key:'sara',   name:'Sara Al-Hassan', email:'sara.alhassan@students.bowiestate.edu',  country:'Egypt',     major:'Public Health' },
  { key:'daniel', name:'Daniel Okafor',  email:'daniel.okafor@students.bowiestate.edu',  country:'Nigeria',   major:'Computer Science' },
  { key:'mei',    name:'Mei Zhang',      email:'mei.zhang@students.bowiestate.edu',      country:'China',     major:'Data Science' },
  { key:'javier', name:'Javier Ruiz',    email:'javier.ruiz@students.bowiestate.edu',    country:'Colombia',  major:'Finance' },
  { key:'fatima', name:'Fatima Noor',    email:'fatima.noor@students.bowiestate.edu',    country:'Pakistan',  major:'Chemistry' },
]
export const DEMO_PASS = 'demo1234'

export const HOUSINGS = [
  { id:1, type:'Off-Campus', title:'Terrapin Ridge Apartments', location:'Bowie, MD',
    distance:'1.3 mi from campus', price:1275, beds:2, baths:1, sqft:850, availability:'Available',
    tags:['Pet Friendly','Washer/Dryer','Parking'],
    desc:'Modern 2-bedroom apartment with updated kitchen, stainless appliances, and hardwood floors. Quick shuttle access to BSU campus. Community gym, pool, and outdoor lounge.',
    amenities:['Gym','Pool','Pet Friendly','Washer/Dryer','Parking','WiFi','Dishwasher','Air Conditioning'],
    img:'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=700&h=420&fit=crop', agent:'Sarah Kim' },
  { id:2, type:'Off-Campus', title:'Campus Walk Studio', location:'Jericho Park Rd, Bowie',
    distance:'0.8 mi from campus', price:980, beds:1, baths:1, sqft:510, availability:'Waitlist',
    tags:['Utilities Included','Furnished','Studio'],
    desc:'Quiet studio apartment with all utilities included and secure building entry. Perfect for a solo student wanting to be close to BSU. Fully furnished.',
    amenities:['All Utilities Included','Furnished','Secure Entry','Laundry Room','Bike Storage','24-Hr Maintenance'],
    img:'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=700&h=420&fit=crop', agent:'Marcus Johnson' },
  { id:3, type:'On-Campus', title:'Christa McAuliffe Hall', location:'BSU Residence Life',
    distance:'On campus', price:760, beds:1, baths:1, sqft:380, availability:'Available',
    tags:['Meal Plan','On Campus','RA Support'],
    desc:'Residence hall suite with student support staff, dining hall access, and vibrant community. Ideal for first-year international students.',
    amenities:['Meal Plan Included','Study Lounges','Computer Lab','Fitness Center','Campus Store','24-Hr Security'],
    img:'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=700&h=420&fit=crop', agent:'BSU Housing Office' },
  { id:4, type:'Off-Campus', title:'Bowie Townhomes', location:'Belair Dr, Bowie',
    distance:'2.4 mi from campus', price:1650, beds:3, baths:2, sqft:1400, availability:'Available',
    tags:['Parking','Family Friendly','Roommates OK'],
    desc:'Spacious townhome, great for 2–3 roommates. Private parking, fenced patio, and full kitchen. Quiet neighborhood.',
    amenities:['Private Parking','Patio','Full Kitchen','In-Unit Laundry','Basement Storage','3 Bedrooms'],
    img:'https://images.unsplash.com/photo-1555854877-bab0e564b8d5?w=700&h=420&fit=crop', agent:'Premier Realty' },
  { id:5, type:'On-Campus', title:'Tubman-Mays Hall', location:'BSU Main Campus',
    distance:'On campus', price:680, beds:1, baths:1, sqft:320, availability:'Limited',
    tags:['Study Lounge','Secure Entry','Events'],
    desc:'Traditional residence hall with community study spaces and regular cultural events. Flexible meal plan options.',
    amenities:['Study Lounges','Community Kitchen','Common Areas','Cultural Events','Mail Service','Campus Shuttle'],
    img:'https://images.unsplash.com/photo-1598928506311-c55ded91a20c?w=700&h=420&fit=crop', agent:'BSU Housing Office' },
  { id:6, type:'Off-Campus', title:'Greenbelt Commons', location:'Greenbelt, MD',
    distance:'6.8 mi from campus', price:1195, beds:2, baths:2, sqft:990, availability:'Available',
    tags:['Metro Access','Gym','Co-working'],
    desc:'Commuter-friendly modern community, 5-min walk from Greenbelt Metro. Fitness center, co-working space, and rooftop deck.',
    amenities:['Metro Access','Rooftop Deck','Gym','Co-working Space','Dog Park','EV Charging'],
    img:'https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=700&h=420&fit=crop', agent:'Metro Property Group' },
  { id:7, type:'Off-Campus', title:'Capitol Heights Garden Apts', location:'Capitol Heights, MD',
    distance:'4.2 mi from campus', price:875, beds:2, baths:1, sqft:720, availability:'Available',
    tags:['Budget Friendly','Metro Nearby','Laundry'],
    desc:'Affordable 2-bedroom close to the Blue/Silver Metro line. Well-maintained building with responsive management.',
    amenities:['Laundry Room','Parking','Metro Access','24-Hr Maintenance','Balcony'],
    img:'https://images.unsplash.com/photo-1570129477492-45c003edd2be?w=700&h=420&fit=crop', agent:'Capitol Properties' },
  { id:8, type:'Off-Campus', title:'University Park Suites', location:'College Park, MD',
    distance:'8.1 mi from campus', price:1425, beds:2, baths:2, sqft:1050, availability:'Available',
    tags:['Furnished','All Utilities','Study Room'],
    desc:'Student-focused complex near UMD with all utilities included. Great for students who want a full community experience.',
    amenities:['All Utilities','Furnished','Study Rooms','Gym','Pool','Shuttle Service'],
    img:'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=700&h=420&fit=crop', agent:'Student Housing LLC' },
]

export const MENTORS = [
  { id:1, name:'Dr. Maya Chen', initials:'MC', role:'STEM Research Mentor', country:'Taiwan', specialty:'Technology',
    tags:['STEM','Research','Internships','Python'], score:97, sessions:312, rating:4.9, avail:'available', verified:true,
    bio:'Former Google researcher and current BSU CS faculty. Guides international students through research, internships, and US tech culture.' },
  { id:2, name:'Jordan Price', initials:'JP', role:'Business & Networking', country:'USA', specialty:'Business',
    tags:['Networking','MBA','Finance','Leadership'], score:94, sessions:189, rating:4.8, avail:'available', verified:true,
    bio:'MBA from Howard University with 8 years in management consulting. Helps students build networks and find US corporate roles.' },
  { id:3, name:'Aisha Bello', initials:'AB', role:'Wellness & Balance Coach', country:'Nigeria', specialty:'Wellness',
    tags:['Wellness','Stress','Adjustment','Culture'], score:92, sessions:247, rating:5.0, avail:'busy', verified:true,
    bio:'International student herself — expert in mental wellness, culture shock support, and building a balanced student life at BSU.' },
  { id:4, name:'Dr. Rafael Gomez', initials:'RG', role:'Academic Research Mentor', country:'Colombia', specialty:'Research',
    tags:['Grad School','Publications','Lab Work','STEM'], score:90, sessions:156, rating:4.7, avail:'available', verified:true,
    bio:'Published researcher with 15+ years at BSU. Helps students apply to grad programs, find research labs, and get published.' },
  { id:5, name:'Nina Brooks', initials:'NB', role:'Career Services Lead', country:'USA', specialty:'Career',
    tags:['Resume','OPT/CPT','Job Search','LinkedIn'], score:96, sessions:423, rating:4.9, avail:'available', verified:true,
    bio:'7 years in BSU Career Services specializing in international student employment authorization and US job market navigation.' },
  { id:6, name:'Carlos Vega', initials:'CV', role:'Immigration Advisor', country:'Mexico', specialty:'Legal',
    tags:['F-1 Visa','OPT','CPT','I-20'], score:95, sessions:278, rating:4.9, avail:'available', verified:true,
    bio:'Immigration specialist who knows every edge case in F-1 visa rules, work authorization, and status maintenance.' },
  { id:7, name:'Priya Narayanan', initials:'PN', role:'Finance & Scholarships', country:'India', specialty:'Finance',
    tags:['Scholarships','Banking','Budget','Taxes'], score:88, sessions:134, rating:4.8, avail:'away', verified:false,
    bio:'Transitioned from India to Wall Street. Expert in student finance, scholarship applications, and US banking setup.' },
  { id:8, name:'Yuki Tanaka', initials:'YT', role:'Tech & Startup Mentor', country:'Japan', specialty:'Technology',
    tags:['Startups','UI/UX','Product','Tech Jobs'], score:87, sessions:167, rating:4.7, avail:'available', verified:false,
    bio:'Co-founded two startups after BSU. Guides students through the US tech job market and startup culture.' },
]

export const LIFECYCLE_STAGES = [
  { key:'prearrival', icon:'fa-plane-departure', title:'Pre-Arrival',  desc:'Get your I-20, visa interview prep, and move-in checklist completed before departure.' },
  { key:'arrival',    icon:'fa-plane-arrival',   title:'Arrival & Orientation', desc:'Attend check-in, submit immigration documents, and complete your first-week setup.' },
  { key:'housing',    icon:'fa-house-chimney',   title:'Housing & Stability', desc:'Secure safe housing, understand your lease, and set up utilities and transportation.' },
  { key:'academics',  icon:'fa-book-open-reader',title:'Academic Momentum', desc:'Meet advisors, maintain full-time enrollment, and use tutoring/writing support early.' },
  { key:'career',     icon:'fa-briefcase',       title:'Career Readiness', desc:'Prepare resume, plan CPT/OPT, and build internship experience before graduation.' },
  { key:'graduation', icon:'fa-user-graduate',   title:'Graduation & Next Steps', desc:'Complete final requirements, apply for post-grad options, and transition with confidence.' },
]

export const FAQS = [
  { cat:'visa',      q:'What is an F-1 visa and how do I maintain my status?', a:'An F-1 visa is a nonimmigrant student visa for full-time academic programs. To maintain it: enroll full-time (12+ credits for undergrads, 9 for grads), maintain a valid passport and I-20, report address changes within 10 days, and only work with proper authorization. Violating any of these can result in status termination.' },
  { cat:'visa',      q:'What is CPT and how do I apply?', a:'Curricular Practical Training (CPT) authorizes F-1 students to work off-campus in positions tied to their major. Requirements: complete one full academic year, obtain a job offer letter, get your advisor\'s signature, and apply through BSU\'s ISO office. Processing takes 5–7 business days.' },
  { cat:'visa',      q:'What is OPT and when should I apply?', a:'Optional Practical Training (OPT) gives F-1 students 12 months of work authorization after graduation. STEM majors can extend to 36 months. Apply up to 90 days before graduation and no later than 60 days after. USCIS processing takes 3–5 months — apply early!' },
  { cat:'housing',   q:'What housing options are near Bowie State?', a:'BSU offers on-campus residence halls including Christa McAuliffe Hall ($760/mo) and Tubman-Mays Hall ($680/mo). Off-campus options include apartments in Bowie, Landover, Capitol Heights, and Greenbelt. Browse the Housing tab for current listings with photos and pricing.' },
  { cat:'housing',   q:'What should I review before signing a lease?', a:'Key items: lease duration and dates, security deposit (typically 1–2 months\' rent), which utilities are included, pet policy, subletting rules, early termination fees, and maintenance procedures. Always read the full lease and get renters insurance (~$10–15/month).' },
  { cat:'financial', q:'How do I open a US bank account as an international student?', a:'You need your passport, I-20, I-94 record, and BSU student ID. Recommended banks near BSU: Capital One (often no SSN required), Bank of America, and PNC. Wise and Revolut are great digital options. Bring original documents — copies are not accepted.' },
  { cat:'financial', q:'What scholarships are available for international students?', a:'BSU offers the International Student Merit Award, Global Excellence Scholarship, and departmental awards. External options include Fulbright, AAUW International Fellowships, and country-specific embassy scholarships. Apply in October–November for the next academic year.' },
  { cat:'financial', q:'How do I file US taxes as an international student?', a:'Most F-1 students are nonresident aliens and must file Form 1040-NR. Even with $0 income, file Form 8843. Use Sprintax — BSU provides access at reduced cost. Deadline is April 15. Never use TurboTax, as it does not support 1040-NR.' },
  { cat:'campus',    q:'What campus resources are available to international students?', a:'BSU offers the Office of International Education (OIE), Counseling Center, Writing Center, Career Center, and Student Health Services. International students also have ESL support, cultural programming via the ISA, peer mentoring, and emergency financial assistance through the Dean of Students office.' },
  { cat:'campus',    q:'How do I get a BSU student ID?', a:'Visit the Campus Card Office in the Student Center with your acceptance letter and passport. Your student ID is required for dining, library, campus events, gym access, and student discounts at many local businesses.' },
  { cat:'campus',    q:'Can I work on campus as an F-1 student?', a:'Yes! F-1 students can work on-campus up to 20 hours/week during the semester and full-time during official school breaks. Common positions include library assistant, dining services, IT helpdesk, tutoring center, and administrative offices. No special authorization needed.' },
  { cat:'visa',      q:'What happens if I travel outside the US?', a:'You need a valid visa stamp in your passport and a travel signature on your I-20 (issued within the last 12 months). Visit the ISO office at least 2 weeks before travel to get your travel signature. If your visa has expired, you\'ll need to renew it at a US embassy before returning.' },
]

export const RESOURCES = [
  { cat:'immigration', icon:'🛂', title:'F-1 Visa Maintenance Guide',      desc:'Complete guide on maintaining F-1 status, enrollment requirements, travel rules, and DSO reporting obligations.', tag:'USCIS',        link:'https://studyinthestates.dhs.gov' },
  { cat:'immigration', icon:'📋', title:'CPT & OPT Authorization',          desc:'Step-by-step CPT and OPT process — eligibility, timelines, employer requirements, and application tips.',            tag:'Work Auth',     link:'https://www.ice.gov/sevis/opt' },
  { cat:'immigration', icon:'📅', title:'I-20 Extension & Transfer',         desc:'How to request an I-20 extension or school transfer, deadlines, and required documentation from your DSO.',          tag:'I-20',          link:'https://studyinthestates.dhs.gov' },
  { cat:'financial',   icon:'🏦', title:'Opening a US Bank Account',         desc:'Best banks for international students near BSU and how to open accounts with or without a Social Security Number.',  tag:'Banking',       link:'https://wise.com' },
  { cat:'financial',   icon:'🎓', title:'Scholarships & Funding',            desc:'Available scholarships at BSU, external funding sources, and tips for writing winning scholarship applications.',     tag:'Scholarships',  link:'https://www.bowiestate.edu/admissions-aid/financial-aid/' },
  { cat:'financial',   icon:'💳', title:'Building US Credit',                desc:'How to build credit history from scratch — secured cards, credit-builder loans, and mistakes to avoid.',             tag:'Credit',        link:'https://www.bowiestate.edu' },
  { cat:'financial',   icon:'📊', title:'Filing US Taxes (1040-NR)',         desc:'Tax filing guide for F-1 students, Sprintax access, Form 8843 instructions, and key deadlines.',                    tag:'Taxes',         link:'https://www.sprintax.com' },
  { cat:'campus',      icon:'🗺️', title:'BSU Campus Orientation',            desc:'Pre-arrival checklist, orientation schedule, what to bring, and how to navigate your first week at Bowie State.',   tag:'Orientation',   link:'https://www.bowiestate.edu' },
  { cat:'campus',      icon:'🚌', title:'Transportation Guide',              desc:'Bus routes, campus shuttle schedule, Metro connections, and how to get around Prince George\'s County affordably.', tag:'Transport',     link:'https://www.bowiestate.edu/campus-life/transportation/' },
  { cat:'campus',      icon:'❤️', title:'Health & Insurance',                desc:'BSU health insurance requirements, waiver process, campus health services, and mental wellness resources.',          tag:'Health',        link:'https://www.bowiestate.edu/campus-life/health-and-wellness/' },
]

export const CONTACTS = [
  { id:1, name:'Nina Brooks (Career)', initials:'NB', preview:'Happy to review your OPT timeline!', time:'2m ago',   online:true },
  { id:2, name:'Dr. Maya Chen',        initials:'MC', preview:'Send your research proposal when ready.', time:'1h ago',   online:true },
  { id:3, name:'BSU Housing Office',   initials:'BH', preview:'Your application has been received.', time:'Yesterday', online:false },
  { id:4, name:'Jordan Price',         initials:'JP', preview:'Great progress on your LinkedIn!', time:'Mon',        online:false },
  { id:5, name:'Aisha Bello',          initials:'AB', preview:'See you at the workshop Friday!', time:'Last week',  online:false },
]

export const CONTACT_INIT_MSGS = {
  1: [
    { role:'recv', text:'Hi! I\'m Nina from BSU Career Services. How can I help you today?', time:'9:00 AM' },
    { role:'sent', text:'Hi Nina! I have questions about my OPT timeline.', time:'9:02 AM' },
    { role:'recv', text:'Happy to review your OPT timeline! Apply up to 90 days before graduation. USCIS takes 3–5 months so apply early. What\'s your expected graduation date?', time:'9:03 AM' },
  ],
  2: [
    { role:'recv', text:'Hello! I\'m Dr. Chen. I\'ve reviewed your background and I think you\'d be great for BSU\'s AI research lab.', time:'Yesterday' },
    { role:'sent', text:'That\'s amazing! What would I need to do to join?', time:'Yesterday' },
    { role:'recv', text:'Send me your research proposal when ready. I\'ll review it and set up a meeting with the lab director.', time:'Yesterday' },
  ],
  3: [
    { role:'recv', text:'Hello, this is the BSU Housing Office. Your application for Christa McAuliffe Hall has been received.', time:'Monday' },
    { role:'sent', text:'Thank you! When will I hear back about availability?', time:'Monday' },
    { role:'recv', text:'You\'re on the waitlist. We expect openings in 2–3 weeks. We\'ll email you directly when a spot becomes available.', time:'Monday' },
  ],
  4: [
    { role:'recv', text:'Hey! Just reviewed your LinkedIn profile. Great progress on your profile! A few more connections and you\'ll be in great shape.', time:'Mon' },
  ],
  5: [
    { role:'recv', text:'Hi! Don\'t forget about our wellness workshop this Friday at 3pm in the Student Center. It\'s really helpful for managing semester stress!', time:'Last week' },
  ],
}

export const TESTIMONIALS = [
  { name:'Amara Diallo',    country:'Senegal',   major:'MBA Finance',      rating:5, quote:'The portal helped me find my apartment and connect with a mentor before I even landed. I felt prepared from day one.' },
  { name:'Wei Liu',         country:'China',     major:'BS Biology',       rating:5, quote:'Maya answered every question I had about my OPT application at 2am. The AI guidance is genuinely accurate and helpful.' },
  { name:'Priyanka Sharma', country:'India',     major:'MS Data Science',  rating:5, quote:'I uploaded my housing listing and three classmates messaged me within an hour. The community here is incredible.' },
  { name:'Emmanuel Nkosi',  country:'Zimbabwe',  major:'BS Engineering',   rating:5, quote:'The lifecycle timeline made my entire BSU journey so much clearer. I always know exactly what I should be doing next.' },
  { name:'Isabella Torres', country:'Colombia',  major:'BS Nursing',       rating:5, quote:'My mentor connected with me on day one and helped me navigate banking, housing, and academic advising simultaneously.' },
  { name:'Takeshi Yamamoto', country:'Japan',    major:'MS Computer Science', rating:5, quote:'From the resource library to the chatbot, everything I needed was right here. Best student portal I\'ve seen.' },
]
